name: Supported Compat Matrix

env:
  K_SOUP_COV_DO: false

on:
  push:
    branches:
      - 'main'
    tags:
      - '!*' # Do not execute on tags
  pull_request:
    branches:
      - '*'
  # Allow manually triggering the workflow.
  workflow_dispatch:

permissions:
  contents: read

# Cancels all previous workflow runs for the same branch that have not yet completed.
concurrency:
  # The concurrency group contains the workflow name and the branch name.
  group: "${{ github.workflow }}-${{ github.ref }}"
  cancel-in-progress: false

jobs:
  test:
    name: Specs - Ruby ${{ matrix.ruby }} ${{ matrix.appraisal }}${{ matrix.name_extra || '' }}
    if: "!contains(github.event.commits[0].message, '[ci skip]') && !contains(github.event.commits[0].message, '[skip ci]')"
    env: # $BUNDLE_GEMFILE must be set at job level, so it is set for all steps
      BUNDLE_GEMFILE: ${{ github.workspace }}/${{ matrix.gemfile }}.gemfile
    runs-on: ubuntu-latest
    continue-on-error: ${{ matrix.experimental || endsWith(matrix.ruby, 'head') }}
    strategy:
      matrix:
        include:
          # Ruby 3.1
          - ruby: "3.1"
            appraisal: "as-7-0"
            taskname: "spec"
            gemfile: "Appraisal.root"
            rubygems: latest
            bundler: latest
          - ruby: "3.1"
            appraisal: "as-7-1"
            taskname: "spec"
            gemfile: "Appraisal.root"
            rubygems: latest
            bundler: latest
          - ruby: "3.1"
            appraisal: "as-7-2"
            taskname: "spec"
            gemfile: "Appraisal.root"
            rubygems: latest
            bundler: latest

          # Ruby 3.2
          - ruby: "3.2"
            appraisal: "as-7-1"
            taskname: "spec"
            gemfile: "Appraisal.root"
            rubygems: latest
            bundler: latest
          - ruby: "3.2"
            appraisal: "as-7-2"
            taskname: "spec"
            gemfile: "Appraisal.root"
            rubygems: latest
            bundler: latest
          - ruby: "3.2"
            appraisal: "as-8-0"
            taskname: "spec"
            gemfile: "Appraisal.root"
            rubygems: latest
            bundler: latest

          # Ruby 3.3
          - ruby: "3.3"
            appraisal: "as-7-2"
            taskname: "spec"
            gemfile: "Appraisal.root"
            rubygems: latest
            bundler: latest
          - ruby: "3.3"
            appraisal: "as-8-0"
            taskname: "spec"
            gemfile: "Appraisal.root"
            rubygems: latest
            bundler: latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Ruby & RubyGems
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
          rubygems: ${{ matrix.rubygems }}
          bundler: ${{ matrix.bundler }}
          bundler-cache: false
      # This will use the BUNDLE_GEMFILE set to matrix.gemfile (i.e. Appraisal.root)
      # We need to do this first to get appraisal installed.
      # NOTE: This does not use the root Gemfile at all.
      - name: Bundle for Appraisal ${{ matrix.appraisal }} (Rails v${{ matrix.rails}})
        run: bundle
      - name: Install Appraisal ${{ matrix.appraisal }} (Rails v${{ matrix.rails}}) dependencies
        run: bundle exec appraisal ${{ matrix.appraisal }} bundle
      - name: Run ${{ matrix.appraisal }} tests via ${{ matrix.taskname }} (Rails v${{ matrix.rails}})
        run: bundle exec appraisal ${{ matrix.appraisal }} bundle exec rake ${{ matrix.taskname }}
